name: Build & Deploy NetBox via Terraform

on:
  push:
    branches: 
      - main

env:
  PROJECT_ID: arboreal-cosmos-440011-r8
  REGION: asia-southeast2
  REPOSITORY_ID: box-registry
  SERVICE_NAME: netbox

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
     

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$SERVICE_NAME:latest .

    - name: Push Docker image
      run: |
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$SERVICE_NAME:latest

    
     
